/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment_student;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Angelina
 */
public class StudentMain extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public StudentMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubmitProject = new javax.swing.JDialog();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        SProjectIDtxt = new javax.swing.JTextField();
        STypetxt = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        SSupervisorIDtxt = new javax.swing.JTextField();
        SSecondtxt = new javax.swing.JTextField();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        SMoodleLinktxt = new javax.swing.JTextField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JButton ClearButton = new javax.swing.JButton();
        javax.swing.JButton AddButton = new javax.swing.JButton();
        RequestPresentation = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        RSupervisorIDtxt = new javax.swing.JTextField();
        javax.swing.JButton Requestbtn = new javax.swing.JButton();
        RProjectIDtxt = new javax.swing.JTextField();
        RSecondtxt = new javax.swing.JTextField();
        RTypetxt = new javax.swing.JTextField();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        RBackbtn = new javax.swing.JButton();
        CheckGrade = new javax.swing.JDialog();
        GBackbtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        GProjecttxt = new javax.swing.JTextField();
        GTypetxt = new javax.swing.JTextField();
        GStatustxt = new javax.swing.JTextField();
        GCheckGradetxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        SubmitProjectbtn = new javax.swing.JButton();
        RequestPresentationbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CheckGradebtn = new javax.swing.JButton();

        jLabel11.setText("SUBMIT PROJECT");

        jLabel3.setText("Project ID");

        jLabel4.setText("Assessment Type");

        jLabel5.setText("Supervisor ID");

        jLabel9.setText("Second Marker ID");

        jLabel6.setText("Moodle Link");

        jLabel7.setText("Submit Date");

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        AddButton.setText("Add Submission");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubmitProjectLayout = new javax.swing.GroupLayout(SubmitProject.getContentPane());
        SubmitProject.getContentPane().setLayout(SubmitProjectLayout);
        SubmitProjectLayout.setHorizontalGroup(
            SubmitProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubmitProjectLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(SubmitProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addGroup(SubmitProjectLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(SubmitProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(SubmitProjectLayout.createSequentialGroup()
                                .addGroup(SubmitProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(55, 55, 55)
                                .addGroup(SubmitProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SMoodleLinktxt)
                                    .addComponent(SProjectIDtxt)
                                    .addComponent(SSupervisorIDtxt)
                                    .addComponent(SSecondtxt)
                                    .addComponent(STypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(SubmitProjectLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(AddButton))
                    .addComponent(jLabel7)
                    .addGroup(SubmitProjectLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        SubmitProjectLayout.setVerticalGroup(
            SubmitProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubmitProjectLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addGroup(SubmitProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SProjectIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SubmitProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(STypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(SubmitProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SSupervisorIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SubmitProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(SSecondtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SubmitProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SMoodleLinktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(42, 42, 42)
                .addGroup(SubmitProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel8.setText("Supervisor ID");

        jLabel12.setText("REQUEST PRESENTATION");

        Requestbtn.setText("Request");
        Requestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestbtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Project ID");

        jLabel13.setText("Assessment Type");

        jLabel14.setText("Second Marker ID");

        jLabel15.setText("Request Presentation Date");

        RBackbtn.setText("Back");
        RBackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RBackbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Requestbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel10))
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(RProjectIDtxt)
                                            .addComponent(RSupervisorIDtxt)
                                            .addComponent(RSecondtxt)
                                            .addComponent(RTypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel15))
                        .addContainerGap(57, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(RProjectIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(RTypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(RSupervisorIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(RSecondtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Requestbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBackbtn))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RequestPresentationLayout = new javax.swing.GroupLayout(RequestPresentation.getContentPane());
        RequestPresentation.getContentPane().setLayout(RequestPresentationLayout);
        RequestPresentationLayout.setHorizontalGroup(
            RequestPresentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        RequestPresentationLayout.setVerticalGroup(
            RequestPresentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        GBackbtn.setText("Back");
        GBackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBackbtnActionPerformed(evt);
            }
        });

        jLabel16.setText("Check Grade");

        jLabel17.setText("Status");

        jLabel18.setText("Grade");

        jLabel19.setText("Submission Type");

        jLabel20.setText("Project ID");

        javax.swing.GroupLayout CheckGradeLayout = new javax.swing.GroupLayout(CheckGrade.getContentPane());
        CheckGrade.getContentPane().setLayout(CheckGradeLayout);
        CheckGradeLayout.setHorizontalGroup(
            CheckGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckGradeLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(CheckGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckGradeLayout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(104, 104, 104))
                        .addGroup(CheckGradeLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(66, 66, 66)))
                    .addGroup(CheckGradeLayout.createSequentialGroup()
                        .addGroup(CheckGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addGroup(CheckGradeLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(CheckGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(GBackbtn))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(CheckGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GTypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GProjecttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GStatustxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GCheckGradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        CheckGradeLayout.setVerticalGroup(
            CheckGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckGradeLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(CheckGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(GProjecttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CheckGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(GTypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CheckGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(GStatustxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CheckGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(GCheckGradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(GBackbtn)
                .addGap(63, 63, 63))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Project ID", "Assessment Type", "Supervisor ID", "Second Marker ID", "Submitted Date", "Requested Presentation Date", "Request Status", "Status", "Grade", "Link"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        SubmitProjectbtn.setText("Submit Project");
        SubmitProjectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitProjectbtnActionPerformed(evt);
            }
        });

        RequestPresentationbtn.setText("Request Presentation");
        RequestPresentationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestPresentationbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome");

        jLabel2.setText("Choose Below Options");

        CheckGradebtn.setText("Check Grade");
        CheckGradebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckGradebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(SubmitProjectbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RequestPresentationbtn)
                                .addGap(40, 40, 40)
                                .addComponent(CheckGradebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubmitProjectbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RequestPresentationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckGradebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
          
        
    }//GEN-LAST:event_Table1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
        FileReader file = new FileReader("D:\\Year 2\\Sem 1\\JAVA\\Assignment\\Assignment\\file.txt");
        BufferedReader reader = new BufferedReader(file);

        DefaultTableModel model = (DefaultTableModel) Table1.getModel();
        String line;
        while ((line = reader.readLine()) != null) {
            String[] values = line.split("/");
            model.addRow(new Object[]{values[0], values[1], values[2], values[3], values[4], values[5], values[6], values[7], values[8], values[9]});
        }

        reader.close();
        file.close();
        
        Table1.getColumnModel().getColumn(4).setMinWidth(0);
        Table1.getColumnModel().getColumn(4).setMaxWidth(0);
        Table1.getColumnModel().getColumn(7).setMinWidth(0);
        Table1.getColumnModel().getColumn(7).setMaxWidth(0);
        Table1.getColumnModel().getColumn(8).setMinWidth(0);
        Table1.getColumnModel().getColumn(8).setMaxWidth(0);
        Table1.getColumnModel().getColumn(9).setMinWidth(0);
        Table1.getColumnModel().getColumn(9).setMaxWidth(0);
       
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_formWindowOpened

    private void SubmitProjectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitProjectbtnActionPerformed
        SubmitProject project = new SubmitProject();
        project.setVisible(true);
        
        String projectid = "2";
        project.SProjectIDtxt.setText(projectid);
        String submissiontype = "FYP";
        project.STypetxt.setText(submissiontype);
        String supervisorid = "2";
        project.SSupervisorIDtxt.setText(supervisorid);
        String secondmarker = "2";
        project.SSecondtxt.setText(secondmarker);
        
    }//GEN-LAST:event_SubmitProjectbtnActionPerformed

    private void RequestPresentationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestPresentationbtnActionPerformed
        TableModel model1 = Table1.getModel();
        int row = Table1.getSelectedRow();
        if(row != -1) {
            RequestPresentation Request = new RequestPresentation();

            String projectid = model1.getValueAt(row,0).toString();
            String assessmentType = model1.getValueAt(row,1).toString();
            String supervisorID = model1.getValueAt(row,2).toString();
            String secondMarkerID = model1.getValueAt(row,3).toString();

            Request.RProjectIDtxt.setText(projectid);
            Request.RTypetxt.setText(assessmentType);
            Request.RSupervisorIDtxt.setText(supervisorID);
            Request.RSecondtxt.setText(secondMarkerID);

            Request.setVisible(true);
            Request.pack();
            Request.setLocationRelativeTo(null);
            Request.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row from the table.");
        }
        
    }//GEN-LAST:event_RequestPresentationbtnActionPerformed

    private void CheckGradebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckGradebtnActionPerformed
        TableModel model1 = Table1.getModel();
        int row = Table1.getSelectedRow();
        Grade grade = new Grade();

        if(row != -1) { 
            String projectid = model1.getValueAt(row,0).toString();
            String submissiontype = model1.getValueAt(row,1).toString();
            String status = model1.getValueAt(row,7).toString();
            String gradestr = model1.getValueAt(row,8).toString();

            grade.GProjecttxt.setText(projectid);
            grade.GTypetxt.setText(submissiontype);
            grade.GStatustxt.setText(status); 
            grade.GCheckGradetxt.setText(gradestr); 
            
            grade.setVisible(true);
            grade.pack();
            grade.setLocationRelativeTo(null);
            grade.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_CheckGradebtnActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed

    }//GEN-LAST:event_ClearButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed

        String projectid = "2";
        String submissiontype = "FYP";
        String supervisorid = "2";
        String secondmarker = "2";
        String requestpresentationdate = "";
        String requeststatus = "";
        String status = "Ongoing";
        String Grade = "";

        String link = SMoodleLinktxt.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("DD-MM-YYYY");
        String submitteddate = dFormat.format(SSubmitDate.getDate());

        if (link.isEmpty()|| submitteddate.isEmpty()) {
            JOptionPane.showMessageDialog(SubmitProject.this,
                "Please enter all the fields",
                "Try Again",
                JOptionPane.ERROR_MESSAGE);
        } else {
            // Create a string to save to the file
            String dataToSave = projectid + "/" + submissiontype + "/" + supervisorid + "/" + secondmarker + "/" + submitteddate + "/" + requestpresentationdate + "/" + requeststatus + "/" + status + "/" + Grade + "/" + link;

            // Save the data to a file
            try {
                FileWriter writer = new FileWriter("D:\\Year 2\\Sem 1\\JAVA\\Assignment\\Assignment\\file.txt", true);
                writer.write(dataToSave + System.lineSeparator());
                writer.close();
                JOptionPane.showMessageDialog(SubmitProject.this,
                    "Submission added successfully",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(SubmitProject.this,
                    "Error adding submission",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }

            dispose();
        }

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_AddButtonActionPerformed

    private void RequestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestbtnActionPerformed

        //not done yet
        //i plan to out sleect row then can directly replace the date with the date i wish
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy"); // 'yyyy' instead of 'YYYY'
        Date date = RequestPresentationDate.getDate();
        if(date == null) {
            JOptionPane.showMessageDialog(this, "Please enter the request presentation date.");
            return;
        }
        String submitteddate = dFormat.format(date);

        TableModel model = StudentMain.Table1.getModel();
        int row = StudentMain.Table1.getSelectedRow();
        model.setValueAt(submitteddate, row, 5);

        this.dispose();;
    }//GEN-LAST:event_RequestbtnActionPerformed

    private void RBackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBackbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_RBackbtnActionPerformed

    private void GBackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBackbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_GBackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CheckGrade;
    private javax.swing.JButton CheckGradebtn;
    private javax.swing.JButton GBackbtn;
    public javax.swing.JTextField GCheckGradetxt;
    public javax.swing.JTextField GProjecttxt;
    public javax.swing.JTextField GStatustxt;
    public javax.swing.JTextField GTypetxt;
    private javax.swing.JButton RBackbtn;
    public javax.swing.JTextField RProjectIDtxt;
    public javax.swing.JTextField RSecondtxt;
    public javax.swing.JTextField RSupervisorIDtxt;
    public javax.swing.JTextField RTypetxt;
    private javax.swing.JDialog RequestPresentation;
    private javax.swing.JButton RequestPresentationbtn;
    private javax.swing.JTextField SMoodleLinktxt;
    public javax.swing.JTextField SProjectIDtxt;
    public javax.swing.JTextField SSecondtxt;
    public javax.swing.JTextField SSupervisorIDtxt;
    public javax.swing.JTextField STypetxt;
    private javax.swing.JDialog SubmitProject;
    private javax.swing.JButton SubmitProjectbtn;
    private javax.swing.JTable Table1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
