/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment_student;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Angelina
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        SubmitProjectbtn = new javax.swing.JButton();
        RequestPresentationbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CheckGradebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Project ID", "Assessment Type", "Supervisor ID", "Second Marker ID", "Submitted Date", "Requested Presentation Date", "Request Status", "Status", "Grade", "Link"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        SubmitProjectbtn.setText("Submit Project");
        SubmitProjectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitProjectbtnActionPerformed(evt);
            }
        });

        RequestPresentationbtn.setText("Request Presentation");
        RequestPresentationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestPresentationbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome");

        jLabel2.setText("Choose Below Options");

        CheckGradebtn.setText("Check Grade");
        CheckGradebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckGradebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(SubmitProjectbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RequestPresentationbtn)
                                .addGap(40, 40, 40)
                                .addComponent(CheckGradebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubmitProjectbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RequestPresentationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckGradebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
          
        
    }//GEN-LAST:event_Table1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
        FileReader file = new FileReader("D:\\Year 2\\Sem 1\\JAVA\\Assignment\\Assignment\\file.txt");
        BufferedReader reader = new BufferedReader(file);

        DefaultTableModel model = (DefaultTableModel) Table1.getModel();
        String line;
        while ((line = reader.readLine()) != null) {
            String[] values = line.split("/");
            model.addRow(new Object[]{values[0], values[1], values[2], values[3], values[4], values[5], values[6], values[7], values[8], values[9]});
        }

        reader.close();
        file.close();
        
        Table1.getColumnModel().getColumn(4).setMinWidth(0);
        Table1.getColumnModel().getColumn(4).setMaxWidth(0);
        Table1.getColumnModel().getColumn(7).setMinWidth(0);
        Table1.getColumnModel().getColumn(7).setMaxWidth(0);
        Table1.getColumnModel().getColumn(8).setMinWidth(0);
        Table1.getColumnModel().getColumn(8).setMaxWidth(0);
        Table1.getColumnModel().getColumn(9).setMinWidth(0);
        Table1.getColumnModel().getColumn(9).setMaxWidth(0);
       
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_formWindowOpened

    private void SubmitProjectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitProjectbtnActionPerformed
        SubmitProject project = new SubmitProject();
        project.setVisible(true);
        
        String projectid = "2";
        project.SProjectIDtxt.setText(projectid);
        String submissiontype = "FYP";
        project.STypetxt.setText(submissiontype);
        String supervisorid = "2";
        project.SSupervisorIDtxt.setText(supervisorid);
        String secondmarker = "2";
        project.SSecondtxt.setText(secondmarker);
        
    }//GEN-LAST:event_SubmitProjectbtnActionPerformed

    private void RequestPresentationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestPresentationbtnActionPerformed
        TableModel model1 = Table1.getModel();
        int row = Table1.getSelectedRow();
        if(row != -1) {
            RequestPresentation Request = new RequestPresentation();

            String projectid = model1.getValueAt(row,0).toString();
            String assessmentType = model1.getValueAt(row,1).toString();
            String supervisorID = model1.getValueAt(row,2).toString();
            String secondMarkerID = model1.getValueAt(row,3).toString();

            Request.RProjectIDtxt.setText(projectid);
            Request.RTypetxt.setText(assessmentType);
            Request.RSupervisorIDtxt.setText(supervisorID);
            Request.RSecondtxt.setText(secondMarkerID);

            Request.setVisible(true);
            Request.pack();
            Request.setLocationRelativeTo(null);
            Request.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row from the table.");
        }
        
    }//GEN-LAST:event_RequestPresentationbtnActionPerformed

    private void CheckGradebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckGradebtnActionPerformed
        TableModel model1 = Table1.getModel();
        int row = Table1.getSelectedRow();
        Grade grade = new Grade();

        if(row != -1) { 
            String projectid = model1.getValueAt(row,0).toString();
            String submissiontype = model1.getValueAt(row,1).toString();
            String status = model1.getValueAt(row,7).toString();
            String gradestr = model1.getValueAt(row,8).toString();

            grade.GProjecttxt.setText(projectid);
            grade.GTypetxt.setText(submissiontype);
            grade.GStatustxt.setText(status); 
            grade.GCheckGradetxt.setText(gradestr); 
            
            grade.setVisible(true);
            grade.pack();
            grade.setLocationRelativeTo(null);
            grade.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_CheckGradebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckGradebtn;
    private javax.swing.JButton RequestPresentationbtn;
    private javax.swing.JButton SubmitProjectbtn;
    private javax.swing.JTable Table1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
